export const MovementType = {
    MOVE_FORWARD: 'MOVE_FORWARD',
    MOVE_BACKWARD: 'MOVE_BACKWARD',
    TURN_LEFT: 'TURN_LEFT',
    TURN_RIGHT: 'TURN_RIGHT',
    STRAFE_LEFT: 'STRAFE_LEFT',
    STRAFE_RIGHT: 'STRAFE_RIGHT'
};